### ISSUE TITLE
Space Invaders Extractor?

### ISSUE THREAD

**Issue by jdl96** [Morten1337/ZAxisLevelTool#1]
Hi,

I am interested in finding unused content from the game "Space Invaders" that was developed by Z-Axis in 1999 and released for the PC, Playstation, and Nintendo 64.

The game uses ZAL and ZSD files. The ZAL files seem to contain the game's models, textures, etc. while the ZSD files contain the game audio. I was wondering if you knew how to extract these files? Is the ZAxisLevelTool able to open these files?

Thanks.

Edit: If you're interested, the PC version can be found here: https://archive.org/details/INVADERS_201903

**Comment by Morten1337** [comment]
Hey,

I doubt that this tool will work for these files out of the box, but there might be some similarities here.

Like mentioned in the README, many of these file formats follow the IFF spec.
So, if this is the case for Space Invaders, you should at least be able to read the basic data-structure.
But, there will probably be a different set of chunk types that you will have to figure out.

Anyways here's there basic ZIFF data-structure:

```
4 bytes | Chunk Type (FourCC)
4 bytes | Chunk Size
N bytes | Chunk Data
```
